const XLSX = require("xlsx")

function getDataList(filePath) {
	const workbook = XLSX.readFile(filePath)
	const data = XLSX.utils.sheet_to_json(workbook.Sheets['Лист1'] || workbook.Sheets['Sheet1'])
	const collection = []
	for (let i = 0; i < data.length; i++) {
		const {
			['Part Number']: partNumber,
			['Brand']: brand,
			['Sales Model Name']: salesModelName,
			['Processor']: processor,
			['Memory Installed']: memory,
			['Storage Installed']: storageInstalled,
			['Graphic']: graphic,
			['Operating System']: operatingSystem,
			['Display']: display,
			['Color']: color,
			['Expansion Slot (includes used)']: expansionSlot,
			['Camera']: camera,
			['Audio']: audio,
			['Wireless Connectivity']: wirelessConnectivity,
			['Interface']: interfaceConnect,
			['Input Device']: inputDevice,
			['Security']: security,
			['Battery and Power']: batteryAndPower,
			['Included in the Box']: includedBox,
			['Weight and Dimension']: weightDimension,
			['Warranty from preconfig']: warrantyPreconfig,
			['Certificate']: certificate,
			['cfg_color']: cfg_color,
			['cpu_vendor']: cpu_vendor,
			['cpu_platform']: cpu_platform,
			['cpu_generation']: cpu_generation,
			['cpu_voltage']: cpu_voltage,
			['cpu_segment']: cpu_segment,
			['cpu_model']: cpu_model,
			['cpu_core']: cpu_core,
			['display_panel_size']: display_panel_size,
			['display_ccf_lcd']: display_ccf_lcd,
			['display_slim_nit']: display_slim_nit,
			['display_resolution']: display_resolution,
			['display_glare']: display_glare,
			['display_3d_ntsc']: display_3d_ntsc,
			['display_touch']: display_touch,
			['display_wide_view']: display_wide_view,
			['display_lcd_code']: display_lcd_code,
			['storage_total']: storage_total,
			['storage_hdd']: storage_hdd,
			['storage_ssd']: storage_ssd,
			['storage_type']: storage_type,
			['memory_spec']: memory_spec,
			['memory_capacity']: memory_capacity,
			['os']: os,
			['vga']: vga,
			['vram']: vram,
			['marketing_name']: marketing_name,
			['KB Language']: kbLanguage,
			['cfg_warranty']: cfg_warranty,
			['weight_with_battery']: weight_with_battery,
			['weight_without_battery']: weight_without_battery,
			['dimension']: dimension,
			['battery']: battery,
			['power']: power,
			['screenpad']: screenpad,
			['numpad']: numpad,
			['display_oled']: display_oled,
			['display_lcd_type']: display_lcd_type,
			['os_platform']: os_platform,
			['pure_os']: pure_os,
			['antivirus']: antivirus,
			['office']: office,
			['chipset']: chipset,
			['form_factor']: form_factor,
			['chassis']: chassis,
			['cfg_fingerprint']: cfg_fingerprint,
			['kb_type']: kb_type,
			['touchpad']: touchpad,
			['dialpad']: dialpad,
			['wwan']: wwan,
			['item_description']: item_description,
			['cfg_security_reader']: cfg_security_reader
		} = data[i]
		if (data[i]['Quality'] === 'ICECAT') {
			collection.push({
				prompt: {
					partNumber,
					brand,
					salesModelName,
					processor,
					memory,
					operatingSystem,
					audio,
					storageInstalled,
					graphic,
					display,
					color,
					expansionSlot,
					camera,
					wirelessConnectivity,
					interfaceConnect,
					inputDevice,
					security,
					batteryAndPower,
					includedBox,
					weightDimension,
					warrantyPreconfig,
					certificate,
					cfg_color,
					cpu_vendor,
					cpu_platform,
					cpu_generation,
					cpu_voltage,
					cpu_segment,
					cpu_model,
					cpu_core,
					display_panel_size,
					display_ccf_lcd,
					display_slim_nit,
					display_resolution,
					display_glare,
					display_3d_ntsc,
					display_touch,
					display_wide_view,
					display_lcd_code,
					storage_total,
					storage_hdd,
					storage_ssd,
					storage_type,
					memory_spec,
					memory_capacity,
					os,
					vga,
					vram,
					marketing_name,
					kbLanguage,
					cfg_warranty,
					weight_with_battery,
					weight_without_battery,
					dimension,
					battery,
					power,
					screenpad,
					numpad,
					display_oled,
					display_lcd_type,
					os_platform,
					pure_os,
					antivirus,
					office,
					chipset,
					form_factor,
					chassis,
					cfg_fingerprint,
					kb_type,
					touchpad,
					dialpad,
					wwan,
					item_description,
					cfg_security_reader
				}
			})
		}

	}
	// console.log(collection)
	return collection
}

function getDataIcecat(filePath) {
	const workbook = XLSX.readFile(filePath)
	const data = XLSX.utils.sheet_to_json(workbook.Sheets['(151) Notebooks'])
	const collection = []
	for (let i = 0; i < data.length; i++) {
		const {
			['Requested part number']: partNumber,
			['Requested brand name']: brandName,
			['** Product type (Text)']: productType,
			['** Product colour (Text)']: productColour,
			['Colour name (Text)']: colourName,
			['* Form factor (Text)']: formFactor,
			['Housing material (Text)']: housingMaterial,
			['Market positioning (Text)']: marketPositioning,
			['Introduction year (Text)']: introductionYear,
			['Country of origin (Text)']: countryOrigin,
//Processor
			['** Processor family (Text)']: ProcessorFamily,
			['* Processor model (Text)']: processorModel,
			['* Processor manufacturer (Text)']: ProcessorManufacturer,
			['Motherboard chipset (Text)']: MotherboardChipset,
			['Processor boost frequency (gigahertz)']: ProcessorBoostFrequency,
			['Processor cores (Text)']: ProcessorCores,
			['* Processor frequency (gigahertz)']: ProcessorFrequency,
			['Processor cache (megabyte)']: ProcessorCache,
			['Processor cache type (Text)']: ProcessorCacheType,
			['Processor generation (Text)']: ProcessorGeneration,
			['Efficient-core boost frequency (gigahertz)']: EfficientCoreBoostFrequency,
//Memory
			['Memory slots (Text)']: memorySlots,
			['* Maximum internal memory (gigabyte)']: maximumInternalMemory,
			['Internal memory type (Text)']: internalMemoryType,
			['Memory clock speed (megahertz)']: memoryClockSpeed,
			['Memory layout (slots x size) (gigabyte)']: memoryLayout,
			['Memory form factor (Text)']: memoryFormFactor,
			['Memory channels (Text)']: memoryChannels,
			['** Internal memory (gigabyte']: internalMemory,
//Audio
			['Audio system (Text)']: audioSystem,
			['Built-in microphone (Y/N)']: builtInMicrophone,
			['Speakers manufacturer (Text)']: speakersManufacturer,
			['Number of built-in speakers (Text)']: numberOfBuiltInSpeakers,
			['Speaker power (Watt)']: speakerPower,
			['Number of microphones (Text)']: numberOfMicrophones,
//Software
			['Trial software (Text)']: trialSoftware,
			['Operating system architecture (Text)']: operatingSystemArchitecture,
			['Windows 11 free upgrade (Y/N)']: windows11FreeUpgrade,
			['** Operating system installed (Text)']: operatingSystemInstalled,
//Display
			['** Display diagonal (inch)']: displayDiagonal,
			['** Display resolution (pixels)']: displayResolution,
			['** Touchscreen (Y/N)']: touchscreen,
			['Foldable display (Y/N)']: foldableDisplay,
			['HD type (Text)']: hdType,
			['Touchscreen type (Text)']: touchscreenType,
			['Panel type (Text)']: panelType,
			['LED backlight (Y/N)']: ledBacklight,
			['Native aspect ratio (Text)']: nativeAspectRatio,
			['Display surface (Text)']: displaySurface,
			['Anti-glare screen (Y/N)']: antiGlareScreen,
			['Display brightness (candellas per square meter)']: displayBrightness,
			['Maximum display brightness (HDR) (candellas per square meter)']: maximumDisplayBrightness,
			['Display diagonal (metric) (centimeter)']: displayDiagonalMetric,
			['RGB colour space (Text)']: rgbColourSpace,
			['Colour gamut (percent)']: colourGamut,
			['Maximum refresh rate (Hertz)']: maximumRefreshRate,
			['Contrast ratio (typical) (Text)']: contrastRatio,
			['High Dynamic Range (HDR) supported (Y/N)']: highDynamicRange,
			['High Dynamic Range (HDR) technology (Text)']: highDynamicRangeTechnology,
//Storage
			['** Total storage capacity (gigabyte)']: totalStorageCapacity,
			['** Storage media (Text)']: storageMedia,
			['Total SSDs capacity (gigabyte)']: totalSSDsCapacity,
			['Number of SSDs installed (Text)']: numberOfSSDsInstalled,
			['SSD capacity (gigabyte)']: SSDcapacity,
			['SSD interface (Text)']: SSDinterface,
			['NVMe (Y/N)']: NVMe,
			['SSD form factor (Text)']: SSDFormFactor,
			['Flash memory (gigabyte)']: flashMemory,
			['Flash drive interface (Text)']: flashDriveInterface,
			['Intel® Optane™ Memory module installed (Y/N)']: intelOptaneMemory,
			['Intel® Optane™ Memory module capacity (gigabyte)']: IntelOptaneMemoryModule,
			['Card reader integrated (Y/N)']: cardReaderIntegrated,
			['Compatible memory cards (Text)']: compatibleMemoryCards,
			['** On-board graphics card (Y/N)']: onboardGraphicsCard,
			['** Discrete graphics card (Y/N)']: discreteGraphicsCard,
			['Discrete GPU manufacturer (Text)']: discreteGPUmanufacturer,
			['* Discrete graphics card model (Text)']: discreteGraphicsCardModel,
			['* On-board graphics card model (Text)']: onboardGraphicsCardModel,
			['Discrete graphics card memory (gigabyte)']: discreteGraphicsCardMemory,
			['Discrete graphics memory type (Text)']: discreteGraphicsMemoryType,
			['NVIDIA Max-Q (Y/N)']: NVIDIAMax,
			['NVIDIA G-SYNC (Y/N)']: NVIDIAGSYNC,
			['AMD FreeSync (Y/N)']: AMDFreeSync,

			['Front camera (Y/N)']: frontCamera,
			['Front camera resolution (numeric) (megapixel)']: frontCameraResolution,
			['Front camera HD type (Text)']: frontCameraHDtype,
			['Infrared (IR) camera (Y/N)']: infraredCamera,
			['Privacy camera (Y/N)']: privacyCamera,
			['Privacy type (Text)']: privacyType,
			['Rear camera (Y/N)']: rearCamera,
			['Rear camera resolution (numeric) (megapixel)']: rearCameraResolution,

			['** Mobile network connection (Y/N)']: mobileNetworkConnection,
			['Mobile network generation (Text)']: mobileNetworkGeneration,
			['* Top Wi-Fi standard (Text)']: topWiFiStandard,
			['Wi-Fi standards (Text)']: WiFiStandards,
			['Antenna type (Text)']: antennaType,
			['Ethernet LAN (Y/N)']: ethernetLan,
			['Ethernet LAN data rates (megabit per second)']: ethernetLANDataRates,
			['Bluetooth (Y/N)']: bluetooth,
			['Bluetooth version (Text)']: bluetoothVersion,
			['Near Field Communication (NFC) (Y/N)']: nearFieldCommunication,
			['* USB 2.0 ports quantity (Text)']: USB2PortsQuantity,
			['* USB 3.2 Gen 1 (3.1 Gen 1) Type-A ports quantity (Text)']: USB3_2Gen1TypeA,
			['* USB 3.2 Gen 1 (3.1 Gen 1) Type-C ports quantity (Text)']: USB3_2Gen1TypeC,
			['USB 3.2 Gen 2 (3.1 Gen 2) Type-A ports quantity (Text)']: USB3_2Gen2TypeA,
			['USB 3.2 Gen 2 (3.1 Gen 2) Type-C ports quantity (Text)']: USB3_2Gen2TypeC,
			['USB4 Gen 2x2 ports quantity (Text)']: USB4Gen2x2,
			['USB4 Gen 3x2 ports quantity (Text)']: USB4Gen3x2,
			['Ethernet LAN (RJ-45) ports (Text)']: ethernetLanRg45,
			['* HDMI ports quantity (Text)']: HDMIportsQuantity,
			['VGA (D-Sub) ports quantity (Text)']: VGAports,
			['Thunderbolt 4 ports quantity (Text)']: Thunderbolt4ports,
			['Intel® Thunderbolt 4 (Y/N)']: intelThunderbolt4,
			['Mini HDMI ports quantity (Text)']: miniHDMIports,
			['Micro HDMI ports quantity (Text)']: microHDMIports,
			['Headphone outputs (Text)']: headphoneOutputs,
			['Combo headphone/mic port (Y/N)']: comboHeadphone_micPort,
			['Charging port type (Text)']: chargingportType,
			['Power adapter barrel connector (Text)']: powerAdapterBarrelConnector,
			['SmartCard slot (Y/N)']: SmartCardSlot,
			['USB Type-C DisplayPort Alternate Mode (Y/N)']: USBTypeCDisplayPort,
			['USB Power Delivery (Y/N)']: USBPowerDelivery,
			['ROG XG Mobile port (Y/N)']: ROGXGMobilePort,
			['Virtual Reality (VR) ready (Y/N)']: virtualReality,
			['Pointing device (Text)']: pointingDevice,
			['Keyboard layout (Text)']: keyboardLayout,
			['Keyboard language (Text)']: keyboardLanguage,
			['* Numeric keypad (Y/N)']: numericKeypad,
			['Keyboard backlit (Y/N)']: keyboardBacklit,
			['Keyboard backlit colour (Text)']: keyboardBacklitColour,
			['Keyboard backlit zone (Text)']: keyboardBacklitZone,
			['Island-style keyboard (Y/N)']: islandStyleKeyboard,
			['Spill-resistant keyboard (Y/N)']: spillResistantKeyboard,
			['Full-size keyboard (Y/N)']: fullsizeKeyboard,
			//Battery
			['Battery technology (Text)']: batteryTechnology,
			['Number of battery cells (Text)']: numberOfBatteryCells,
			['* Battery capacity (Watt-hour)']: batteryCapacity,
			['Removable battery (Y/N)']: removableBattery,
			['Battery weight (gram)']: batteryWeight,
			['AC adapter power (Watt)']: acAdapterPower,
			['AC adapter frequency (Hertz)']: acAdapterFrequency,
			['AC adapter input voltage (Volt)']: acAdapterInputVoltage,
			['AC adapter output current (Ampere)']: acAdapterOutputCurrent,
			['AC adapter output voltage (Volt)']: acAdapterOutputVoltage,
			['Cable lock slot (Y/N)']: cableLockSlot,
			['Cable lock slot type (Text)']: cableLockSlotType,
			['Fingerprint reader (Y/N)']: fingerprintReader,
			['Face recognition (Y/N)']: faceRecognition,
			['Windows Hello (Y/N)']: windowsHello,
			['Trusted Platform Module (TPM) (Y/N)']: trustedPlatformModule,
			['Trusted Platform Module (TPM) version (Text)']: trustedPlatformModuleVersion,
			['Password protection (Y/N)']: passwordProtection,
			['Password protection type (Text)']: passwordProtectionType,
			['Certification (Text)']: certification,
			//gabarits
			['** Weight (gram)']: Feature94INT,
			['Width (millimeter)']: Feature1649INT,
			['Depth (millimeter)']: Feature1650INT,
			['Height (millimeter)']: Feature1464INT,
			['Height (front) (millimeter)']: Feature5702INT,
			['Height (rear) (millimeter)']: Feature5703INT,
			['Package width (millimeter)']: Feature3808INT,
			['Package depth (millimeter)']: Feature3806INT,
			['Package height (millimeter)']: Feature3807INT,
			['Package weight (gram)']: Feature762INT,
			['Mouse included (Y/N)']: Feature2944INT,
			['Mouse connectivity (Text)']: Feature45581INT,
			['Bag included (Y/N)']: Feature6230INT,
			['Stylus pen (Y/N)']: Feature8064INT,
			['Interface adapters included (Text)']: Feature8576INT,
			['Wrist rest (Y/N)']: Feature8394INT,
			['Harmonized System (HS) code (Text)']: Feature23731INT,
			['Repairability index (Text)']: Feature42930INT
		} = data[i]
		const dataForLearning = {
			completion: {
				partNumber,
				brandName,
				productType,
				productColour,
				colourName,
				formFactor,
				housingMaterial,
				marketPositioning,
				introductionYear,
				countryOrigin,
				ProcessorFamily,
				processorModel,
				ProcessorManufacturer,
				MotherboardChipset,
				ProcessorBoostFrequency,
				ProcessorCores,
				ProcessorFrequency,
				ProcessorCache,
				ProcessorCacheType,
				ProcessorGeneration,
				EfficientCoreBoostFrequency,
				memorySlots,
				maximumInternalMemory,
				internalMemoryType,
				memoryClockSpeed,
				memoryLayout,
				memoryFormFactor,
				memoryChannels,
				internalMemory,
				audioSystem,
				builtInMicrophone,
				speakersManufacturer,
				numberOfBuiltInSpeakers,
				speakerPower,
				numberOfMicrophones,
				trialSoftware,
				operatingSystemArchitecture,
				windows11FreeUpgrade,
				operatingSystemInstalled,
				displayDiagonal,
				displayResolution,
				touchscreen,
				foldableDisplay,
				hdType,
				touchscreenType,
				panelType,
				ledBacklight,
				nativeAspectRatio,
				displaySurface,
				antiGlareScreen,
				displayBrightness,
				maximumDisplayBrightness,
				displayDiagonalMetric,
				rgbColourSpace,
				colourGamut,
				maximumRefreshRate,
				contrastRatio,
				highDynamicRange,
				highDynamicRangeTechnology,
				totalStorageCapacity,
				storageMedia,
				totalSSDsCapacity,
				numberOfSSDsInstalled,
				SSDcapacity,
				SSDinterface,
				NVMe,
				SSDFormFactor,
				flashMemory,
				flashDriveInterface,
				intelOptaneMemory,
				IntelOptaneMemoryModule,
				cardReaderIntegrated,
				compatibleMemoryCards,
				onboardGraphicsCard,
				discreteGraphicsCard,
				discreteGPUmanufacturer,
				discreteGraphicsCardModel,
				onboardGraphicsCardModel,
				discreteGraphicsCardMemory,
				discreteGraphicsMemoryType,
				NVIDIAMax,
				NVIDIAGSYNC,
				AMDFreeSync,
				frontCamera,
				frontCameraResolution,
				frontCameraHDtype,
				infraredCamera,
				privacyCamera,
				privacyType,
				rearCamera,
				rearCameraResolution,
				mobileNetworkConnection,
				mobileNetworkGeneration,
				topWiFiStandard,
				WiFiStandards,
				antennaType,
				ethernetLan,
				ethernetLANDataRates,
				bluetooth,
				bluetoothVersion,
				nearFieldCommunication,
				USB2PortsQuantity,
				USB3_2Gen1TypeA,
				USB3_2Gen1TypeC,
				USB3_2Gen2TypeA,
				USB3_2Gen2TypeC,
				USB4Gen2x2,
				USB4Gen3x2,
				ethernetLanRg45,
				HDMIportsQuantity,
				VGAports,
				Thunderbolt4ports,
				intelThunderbolt4,
				miniHDMIports,
				microHDMIports,
				headphoneOutputs,
				comboHeadphone_micPort,
				chargingportType,
				powerAdapterBarrelConnector,
				SmartCardSlot,
				USBTypeCDisplayPort,
				USBPowerDelivery,
				ROGXGMobilePort,
				virtualReality,
				pointingDevice,
				keyboardLayout,
				keyboardLanguage,
				numericKeypad,
				keyboardBacklit,
				keyboardBacklitColour,
				keyboardBacklitZone,
				islandStyleKeyboard,
				spillResistantKeyboard,
				fullsizeKeyboard,
				batteryTechnology,
				numberOfBatteryCells,
				batteryCapacity,
				removableBattery,
				batteryWeight,
				acAdapterPower,
				acAdapterFrequency,
				acAdapterInputVoltage,
				acAdapterOutputCurrent,
				acAdapterOutputVoltage,
				cableLockSlot,
				cableLockSlotType,
				fingerprintReader,
				faceRecognition,
				windowsHello,
				trustedPlatformModule,
				trustedPlatformModuleVersion,
				passwordProtection,
				passwordProtectionType,
				certification,
				Feature94INT,
				Feature1649INT,
				Feature1650INT,
				Feature1464INT,
				Feature5702INT,
				Feature5703INT,
				Feature3808INT,
				Feature3806INT,
				Feature3807INT,
				Feature762INT,
				Feature2944INT,
				Feature45581INT,
				Feature6230INT,
				Feature8064INT,
				Feature8576INT,
				Feature8394INT,
				Feature23731INT,
				Feature42930INT
			}
		}
		collection.push(dataForLearning)
		// console.log(dataForLearning)
	}

	return collection
}
module.exports = {
	getDataIcecat, getDataList
}
